import test from 'node:test';import assert from 'node:assert/strict';import { buildStoryParameters,createInitialState,getActiveEffects,resolvePauseParameters } from './engine.ts';import { naoSouciStory } from './naoSouciStory.ts';import type { StoryPause } from './types.ts'
import { storyReducer } from './StoryStateReducer.ts'
test('getActiveEffects supports overlaps and boundaries',()=>{const effects=[{id:'a',start:0,duration:10,effect:'mist' as const},{id:'b',start:5,duration:10,effect:'roots' as const}];assert.deepEqual(getActiveEffects(effects,6).map(e=>e.id),['a','b']);assert.equal(getActiveEffects(effects,15).length,0)})
test('resolvePauseParameters respects max choices',()=>{const pause=naoSouciStory.steps[1] as StoryPause;assert.deepEqual(resolvePauseParameters(pause,['mist','storm','night']),{fogDensity:.7,waveIntensity:1,windIntensity:.9,darkness:.35})})
test('buildStoryParameters merges projective responses',()=>{const result=buildStoryParameters(naoSouciStory,{'ocean-resonance':['mist'],'resource-resonance':['support']});assert.equal(result.fogDensity,.7);assert.equal(result.stability,1)})
test('initial state supports restart and resume defaults',()=>{const state=createInitialState('nao-souci');assert.equal(state.currentStepIndex,0);assert.equal(state.isPaused,false);assert.deepEqual(state.responses,{})})
test('scene progression pauses, resumes and resets',()=>{let state=storyReducer(createInitialState('nao-souci'),{type:'START'});state=storyReducer(state,{type:'TICK',delta:4});assert.equal(state.currentSceneTime,4);state=storyReducer(state,{type:'TOGGLE_PAUSE'});assert.equal(storyReducer(state,{type:'TICK',delta:2}).currentSceneTime,4);state=storyReducer(state,{type:'TOGGLE_PAUSE'});state=storyReducer(state,{type:'NEXT'});assert.equal(state.currentStepIndex,1);assert.equal(state.currentSceneTime,0);state=storyReducer(state,{type:'RESTART'});assert.equal(state.currentStepIndex,0)})
test('projective responses remain data-only selections',()=>{const state=storyReducer(createInitialState('nao-souci'),{type:'RESPOND',pauseId:'ocean-resonance',ids:['mist','swell']});assert.deepEqual(state.responses,{'ocean-resonance':['mist','swell']})})
test('beta scenes total 36 seconds and use four-second cues',()=>{const scenes=naoSouciStory.steps.filter(step=>step.type==='scene');assert.equal(scenes.reduce((total,scene)=>total+scene.duration,0),36);for(const scene of scenes){assert.equal(scene.duration,12);assert.equal(scene.media.loopDuration,12);for(const cue of scene.effects){assert.equal(cue.start%4,0);assert.equal(cue.duration%4,0)}}})
