import test from 'node:test';import assert from 'node:assert/strict';import { buildStoryParameters,createInitialState,getActiveEffects,resolvePauseParameters } from './engine.ts';import { naoSouciStory } from './naoSouciStory.ts';import type { StoryPause } from './types.ts'
import { storyReducer } from './StoryStateReducer.ts'
test('getActiveEffects supports overlaps and boundaries',()=>{const effects=[{id:'a',start:0,duration:10,effect:'mist' as const},{id:'b',start:5,duration:10,effect:'roots' as const}];assert.deepEqual(getActiveEffects(effects,6).map(e=>e.id),['a','b']);assert.equal(getActiveEffects(effects,15).length,0)})
test('resolvePauseParameters respects max choices',()=>{const pause=naoSouciStory.steps.find(step=>step.type==='pause') as StoryPause;assert.deepEqual(resolvePauseParameters(pause,['seed','leaf']),{growthSpeed:1.1})})
test('buildStoryParameters merges projective responses',()=>{const result=buildStoryParameters(naoSouciStory,{'ocean-resonance':['twig'],'resource-resonance':['light'],'navigation-resonance':['waves']});assert.equal(result.stability,.9);assert.equal(result.lightIntensity,1);assert.equal(result.waveIntensity,.65)})
test('initial state supports restart and resume defaults',()=>{const state=createInitialState('nao-souci');assert.equal(state.currentStepIndex,0);assert.equal(state.isPaused,false);assert.deepEqual(state.responses,{})})
test('scene progression pauses, resumes and resets',()=>{let state=storyReducer(createInitialState('nao-souci'),{type:'START'});state=storyReducer(state,{type:'TICK',delta:4});assert.equal(state.currentSceneTime,4);state=storyReducer(state,{type:'TOGGLE_PAUSE'});assert.equal(storyReducer(state,{type:'TICK',delta:2}).currentSceneTime,4);state=storyReducer(state,{type:'TOGGLE_PAUSE'});state=storyReducer(state,{type:'NEXT'});assert.equal(state.currentStepIndex,1);assert.equal(state.currentSceneTime,0);state=storyReducer(state,{type:'RESTART'});assert.equal(state.currentStepIndex,0)})
test('projective responses remain data-only selections',()=>{const state=storyReducer(createInitialState('nao-souci'),{type:'RESPOND',pauseId:'ocean-resonance',ids:['mist','swell']});assert.deepEqual(state.responses,{'ocean-resonance':['mist','swell']})})
test('final story contains the prologue, five acts and three questions',()=>{const scenes=naoSouciStory.steps.filter(step=>step.type==='scene');const pauses=naoSouciStory.steps.filter(step=>step.type==='pause');assert.equal(scenes.length,6);assert.equal(pauses.length,3);assert.equal(scenes[0].title,'Prologue');assert.match(scenes.at(-1)!.title,/Acte V/);assert.ok(scenes.every(scene=>scene.manualAdvance))})
test('scenes target available public story media',()=>{const scenes=naoSouciStory.steps.filter(step=>step.type==='scene');assert.ok(scenes.every(scene=>['/story/drift.mp4','/story/growth.mp4','/story/navigation.mp4'].includes(scene.media.video!)))})
test('each final choice provides its resonance text',()=>{const pauses=naoSouciStory.steps.filter(step=>step.type==='pause');assert.equal(pauses.flatMap(pause=>pause.options).length,9);assert.ok(pauses.every(pause=>pause.options.every(option=>option.resonance?.title.startsWith('Résonance'))))})
