import type { EffectCue, StoryDefinition } from './types'

const cues = (items: Array<[string, number, number, EffectCue['effect'], number?]>): EffectCue[] => items.map(([id,start,duration,effect,intensity=1])=>({id,start,duration,effect,intensity}))

export const naoSouciStory:StoryDefinition={
 id:'nao-souci', title:'La petite noix qui apprit à naviguer sur l’Océan des Soucis', subtitle:'Le conte reste le même. La traversée devient personnelle.', steps:[
  {type:'scene',id:'drift',title:'La dérive',duration:30,text:'Depuis longtemps, un vieux marin glissait sur l’Océan des Soucis. Parmi les lignes lentes de l’eau, une petite demi-coquille de noix dérivait sans bruit.',media:{video:'/story/nao-souci/01-drift.mp4',fallbackSceneId:'drift'},effects:cues([['wash',0,15,'blue-wash'],['wind',5,20,'wind-lines'],['mist',15,15,'mist']]),transitionIn:'fade',transitionOut:'ink-wash'},
  {type:'pause',id:'ocean-resonance',title:'Une pause sur l’eau',question:'Si cet Océan ressemblait un peu à ce que vous traversez aujourd’hui, à quoi ressemblerait-il ?',helperText:'Choisissez jusqu’à deux résonances. Elles ne changent pas le récit.',maxChoices:2,allowSkip:true,options:[['mist','Brume',{fogDensity:.7}],['swell','Houle',{waveIntensity:.75}],['against','Courant contraire',{horizontalDrift:-.55,windIntensity:.45}],['night','Nuit',{darkness:.7}],['storm','Tempête',{waveIntensity:1,windIntensity:.9,darkness:.35}],['still','Mer immobile',{waveIntensity:.04}],['none','Rien pour l’instant',{}]].map(([id,label,params])=>({id:id as string,label:label as string,params:params as Record<string,number>}))},
  {type:'scene',id:'growth',title:'Le vivant apparaît',duration:30,text:'Feuilles, bois et terre se mêlèrent à la pluie et au soleil. Dans l’humus patient, une graine s’ouvrit. Des racines descendirent. Une tige chercha lentement la lumière.',media:{video:'/story/nao-souci/02-growth.mp4',fallbackSceneId:'growth'},effects:cues([['earth',0,10,'earth'],['seed',5,10,'seed'],['roots',10,15,'roots'],['stem',18,12,'stem']]),transitionIn:'paper-dissolve',transitionOut:'ink-wash'},
  {type:'pause',id:'resource-resonance',title:'Ce que la traversée dépose',question:'Parmi ce que la traversée a déposé, qu’est-ce qui pourrait devenir une ressource ?',helperText:'Une seule résonance suffit.',maxChoices:1,allowSkip:true,options:[['presence','Une présence',{stability:.75}],['word','Une parole',{windIntensity:.35}],['memory','Un souvenir',{lightIntensity:.55}],['idea','Une idée',{lightIntensity:.8}],['value','Une valeur',{stability:.65}],['limit','Une limite',{stability:.9}],['support','Un appui',{stability:1}],['waiting','Une attente',{growthSpeed:.65}],['none','Rien pour l’instant',{}]].map(([id,label,params])=>({id:id as string,label:label as string,params:params as Record<string,number>}))},
  {type:'scene',id:'navigation',title:'La navigation',duration:30,text:'La fleur de souci devint un mât vivant et une voile naturelle. Les racines stabilisaient la terre. La noix apprenait à naviguer. Le vieux marin révéla enfin son nom : Nao Souci.',media:{video:'/story/nao-souci/03-navigation.mp4',fallbackSceneId:'navigation'},effects:cues([['flower',0,12,'flower'],['motion',7,23,'forward-motion'],['wind',10,20,'wind-lines'],['horizon',18,12,'horizon-light']]),transitionIn:'fade',transitionOut:'paper-dissolve'},
  {type:'ending',id:'shore',title:'La traversée s’arrête ici pour aujourd’hui.',text:'Devant Nao Souci, l’horizon reste ouvert.'}
 ]
}
