/* eslint-disable react-refresh/only-export-components */
import { createContext,useCallback,useContext,useEffect,useMemo,useReducer,useRef,type ReactNode } from 'react'
import { buildStoryParameters,createInitialState } from './engine'
import { clearStoryProgress,loadStoryProgress,saveStoryProgress } from './storage'
import type { ResolvedSceneMedia,StoryDefinition,StoryRuntimeState } from './types'
import { storyReducer } from './StoryStateReducer'

interface StoryContextValue{definition:StoryDefinition;state:StoryRuntimeState;start:()=>void;next:()=>void;togglePause:()=>void;respond:(id:string,ids:string[])=>void;setMedia:(media?:ResolvedSceneMedia,error?:string)=>void;restart:(home?:boolean)=>void;review:()=>void}
const StoryContext=createContext<StoryContextValue|undefined>(undefined)
export function StoryStateProvider({definition,children}:{definition:StoryDefinition;children:ReactNode}){const[state,dispatch]=useReducer(storyReducer,definition.id,createInitialState);const frame=useRef(0);const previous=useRef(0)
 useEffect(()=>{const saved=loadStoryProgress();if(saved&&saved.currentStepIndex<definition.steps.length)dispatch({type:'RESTORE',state:{currentStepIndex:saved.currentStepIndex,responses:saved.responses,completed:saved.completed,started:saved.currentStepIndex>0,isPlaying:saved.currentStepIndex>0}})},[definition.steps.length])
 useEffect(()=>{const loop=(now:number)=>{if(previous.current)dispatch({type:'TICK',delta:Math.min((now-previous.current)/1000,.1)});previous.current=now;frame.current=requestAnimationFrame(loop)};frame.current=requestAnimationFrame(loop);return()=>cancelAnimationFrame(frame.current)},[])
 const parameters=useMemo(()=>buildStoryParameters(definition,state.responses),[definition,state.responses]);const currentStep=definition.steps[state.currentStepIndex];const stepDuration=currentStep?.type==='scene'?currentStep.duration:1;const progress=(state.currentStepIndex+Math.min(1,state.currentSceneTime/stepDuration))/definition.steps.length;const enriched=useMemo(()=>({...state,parameters,progress}),[state,parameters,progress])
 useEffect(()=>{saveStoryProgress({currentStepIndex:state.currentStepIndex,responses:state.responses,date:new Date().toISOString(),completed:state.completed})},[state.currentStepIndex,state.responses,state.completed])
 const start=useCallback(()=>dispatch({type:'START'}),[]);const next=useCallback(()=>dispatch({type:'NEXT'}),[]);const togglePause=useCallback(()=>dispatch({type:'TOGGLE_PAUSE'}),[]);const respond=useCallback((pauseId:string,ids:string[])=>dispatch({type:'RESPOND',pauseId,ids}),[]);const setMedia=useCallback((media?:ResolvedSceneMedia,error?:string)=>dispatch({type:'MEDIA',media,error}),[]);const restart=useCallback((home=false)=>{clearStoryProgress();dispatch({type:'RESTART',home})},[]);const review=useCallback(()=>{dispatch({type:'RESTART'});dispatch({type:'START'})},[]);const value=useMemo<StoryContextValue>(()=>({definition,state:enriched,start,next,togglePause,respond,setMedia,restart,review}),[definition,enriched,start,next,togglePause,respond,setMedia,restart,review]);return <StoryContext.Provider value={value}>{children}</StoryContext.Provider>}
export function useStoryState(){const context=useContext(StoryContext);if(!context)throw new Error('useStoryState doit être utilisé dans StoryStateProvider');return context}
