import type { OceanChoice, ResourceChoice, SceneConfig, VisualMood } from './types'

export const storyScenes: SceneConfig[] = [
  {id:'drift',title:'La dérive',media:'/story/01-drift.mp4',durationMs:30000,palette:['#dce7e3','#809ca0','#c29b72'],effects:['ocean','shell'],narration:'Depuis longtemps, un vieux marin glissait sur l’Océan des Soucis. Ce jour-là, parmi les lignes lentes de l’eau, il aperçut une petite demi-coquille de noix. Elle dérivait sans bruit, assez légère pour suivre la mer.'},
  {id:'growth',title:'Le vivant apparaît',media:'/story/02-growth.mp4',durationMs:30000,palette:['#d6dfc9','#81956d','#b27e54'],effects:['rain','leaves','growth'],narration:'La traversée déposa des feuilles, un peu de bois et de terre. La pluie les mêla, le soleil les réchauffa. Dans cet humus patient, une graine s’ouvrit. Des racines descendirent. Une tige chercha lentement la lumière.'},
  {id:'navigation',title:'La navigation',media:'/story/03-navigation.mp4',durationMs:30000,palette:['#dfe8dc','#718f8d','#d7a957'],effects:['sail','roots','horizon'],narration:'La fleur de souci grandit au rythme de l’eau. Sa tige devint un mât vivant, ses pétales une voile naturelle. Sous elle, les racines tenaient la terre. La noix apprenait la mer. Le vieux marin sourit enfin : il s’appelait Nao Souci. Devant eux, l’horizon restait ouvert.'},
]
export const oceanChoices:OceanChoice[]=['Brume','Houle','Courant contraire','Nuit','Tempête','Mer immobile','Rien pour l’instant']
export const resourceChoices:ResourceChoice[]=['Une présence','Une parole','Un souvenir','Une idée','Une valeur','Une limite','Un appui','Rien pour l’instant']
export const baseMood:VisualMood={mist:.18,waves:.35,darkness:.05,current:.2,warmth:.45,roots:.45}
export function moodForOcean(choice?:OceanChoice):VisualMood { const mood={...baseMood}; if(choice==='Brume')mood.mist=.8;if(choice==='Houle')mood.waves=.85;if(choice==='Courant contraire')mood.current=.9;if(choice==='Nuit')mood.darkness=.68;if(choice==='Tempête'){mood.waves=1;mood.darkness=.45}if(choice==='Mer immobile')mood.waves=.06;return mood }
export function moodForResource(choice?:ResourceChoice):VisualMood { const mood={...baseMood,warmth:.62}; const index=resourceChoices.indexOf(choice ?? 'Rien pour l’instant'); mood.warmth=.38+(Math.max(index,0)%4)*.14; mood.roots=(choice==='Une limite'||choice==='Un appui')?.9:.5; mood.mist=choice==='Un souvenir'?.42:.12; return mood }
