import assert from 'node:assert/strict'
import test from 'node:test'
import { buildWordPairKey, defaultResourcePhrase, resolveResourcePhrase } from '../data/resourcePhrases.ts'
import { applyTapImpulse, detectWordCollision, initializeWordPetals, limitWordSpeed, readFloatingWordsStorage, selectFloatingWords, separateWordPair } from './floatingWordsMotion.ts'

test('buildWordPairKey is order independent', () => { assert.equal(buildWordPairKey('observer', 'respirer'), 'observer|respirer'); assert.equal(buildWordPairKey('respirer', 'observer'), 'observer|respirer') })
test('resolves requested phrases and fallback', () => { assert.match(resolveResourcePhrase('observer', 'respirer'), /chemin/); assert.match(resolveResourcePhrase('attendre', 'grandir'), /temps/); assert.match(resolveResourcePhrase('sadapter', 'garder-le-cap'), /direction/); assert.equal(resolveResourcePhrase('observer', 'avancer'), defaultResourcePhrase) })
test('selects 8 to 10 unique words', () => { const words = selectFloatingWords('seed', 9); assert.equal(words.length, 9); assert.equal(new Set(words.map(word => word.id)).size, 9) })
test('initializes positions and reduced motion static petals', () => { const petals = initializeWordPetals(900, 700, false, 'a'); assert.equal(petals.length, 9); assert.ok(petals.every(petal => petal.position.x >= 0 && petal.position.y >= 0)); const fixed = initializeWordPetals(900, 700, true, 'a'); assert.ok(fixed.every(petal => petal.velocity.x === 0 && petal.velocity.y === 0)) })
test('tap impulse changes nearby petals and clamps speed', () => { const [petal] = initializeWordPetals(900, 700, false, 'tap'); const changed = applyTapImpulse([petal], { x: petal.position.x, y: petal.position.y }, false); assert.notDeepEqual(changed[0].velocity, petal.velocity); assert.ok(Math.hypot(limitWordSpeed({ ...petal, velocity: { x: 9, y: 9 } }).velocity.x, limitWordSpeed({ ...petal, velocity: { x: 9, y: 9 } }).velocity.y) <= 0.08001) })
test('detects collision, blocks during phrase, honors cooldown and recent pairs', () => { const petals = initializeWordPetals(900, 700, true, 'collision'); petals[0].position = { x: 10, y: 10 }; petals[1].position = { x: 18, y: 18 }; const event = detectWordCollision(petals, 3000, false, [], 0); assert.ok(event); assert.equal(detectWordCollision(petals, 3000, true, [], 0), null); petals[0].cooldownUntil = 5000; assert.equal(detectWordCollision(petals, 3000, false, [], 0), null); petals[0].cooldownUntil = 0; assert.equal(detectWordCollision(petals, 3000, false, [buildWordPairKey(petals[0].id, petals[1].id)], 0), null) })
test('separates pair with cooldown and invalid localStorage falls back', () => { const petals = initializeWordPetals(900, 700, true, 'separate'); const event = { firstId: petals[0].id, secondId: petals[1].id, position: { x: 0, y: 0 }, phrase: 'x', createdAt: 1 }; const separated = separateWordPair(petals, event, 100); assert.equal(separated[0].cooldownUntil, 9100); assert.equal(separated[1].cooldownUntil, 9100); const storage = { getItem: () => '{bad', setItem: () => undefined } as unknown as Storage; assert.deepEqual(readFloatingWordsStorage(storage), { discoveredPairs: [], discoveredPhrases: [], visitCount: 0 }) })
test('three discovered pairs is enough for the free ending controls', () => { assert.equal(['a', 'b', 'c'].length >= 3, true) })
