import assert from 'node:assert/strict'
import test from 'node:test'
import { buildPairKey, defaultResonanceText, resolveResonanceText } from '../data/resonancePairs.ts'
import { applyRippleImpulse, detectCollision, initializeBubbles, limitVelocity, readResonanceSurfaceStorage, selectVisibleBubbles } from './resonanceSurfacePhysics.ts'

test('buildPairKey is order independent', () => { assert.equal(buildPairKey('seed','rain'), 'rain|seed'); assert.equal(buildPairKey('rain','seed'), 'rain|seed') })
test('resolves known and fallback projective phrases', () => { assert.match(resolveResonanceText('seed','rain'), /bonnes conditions/); assert.match(resolveResonanceText('wind','flower'), /vent/); assert.equal(resolveResonanceText('seed','waves'), defaultResonanceText) })
test('initializes at most six unique bubbles and supports reduced motion', () => { const moving = initializeBubbles(800,600,false,'a'); assert.equal(moving.length, 6); assert.equal(new Set(moving.map(b => b.id)).size, 6); const fixed = initializeBubbles(800,600,true,'a'); assert.ok(fixed.every(b => b.velocity.x === 0 && b.velocity.y === 0)) })
test('detects simple collision and blocks simultaneous collision during phrase', () => { const bubbles = initializeBubbles(800,600,true,'a'); bubbles[0].position={x:10,y:10}; bubbles[1].position={x:20,y:20}; assert.ok(detectCollision(bubbles, 3000, false, [], 0)); assert.equal(detectCollision(bubbles, 3000, true, [], 0), null) })
test('honors cooldown and recent pair history', () => { const bubbles = initializeBubbles(800,600,true,'a'); bubbles[0].position={x:10,y:10}; bubbles[1].position={x:20,y:20}; bubbles[0].cooldownUntil=5000; assert.equal(detectCollision(bubbles, 3000, false, [], 0), null); bubbles[0].cooldownUntil=0; assert.equal(detectCollision(bubbles, 3000, false, [buildPairKey(bubbles[0].id,bubbles[1].id)], 0), null) })
test('tap impulse changes velocity but clamps speed', () => { const bubbles = initializeBubbles(800,600,true,'a'); const changed = applyRippleImpulse(bubbles, {x:0,y:0}, false, 1000, 9); assert.ok(changed.some((b,i) => b.velocity.x !== bubbles[i].velocity.x || b.velocity.y !== bubbles[i].velocity.y)); assert.ok(changed.every(b => Math.hypot(b.velocity.x,b.velocity.y) <= .16001)); assert.ok(Math.hypot(limitVelocity({...bubbles[0], velocity:{x:4,y:4}}).velocity.x, limitVelocity({...bubbles[0], velocity:{x:4,y:4}}).velocity.y) <= .16001) })
test('selection rotation has no duplicates and invalid localStorage falls back', () => { assert.equal(new Set(selectVisibleBubbles('stable').map(b => b.id)).size, 6); const storage = { getItem: () => '{bad', setItem: () => undefined } as unknown as Storage; assert.deepEqual(readResonanceSurfaceStorage(storage), { discoveredPairs: [], discoveredTexts: [], visitCount: 0 }) })
