import { useEffect,useRef } from 'react'
import type { ActiveEffect,SceneId,StoryVisualParameters } from '../types'
interface Props{sceneId:SceneId;time:number;parameters:StoryVisualParameters;effects:ActiveEffect[]}
export function PlaceholderStage({sceneId,time,parameters,effects}:Props){const canvas=useRef<HTMLCanvasElement>(null)
 useEffect(()=>{const el=canvas.current;if(!el)return;const ctx=el.getContext('2d');if(!ctx)return;const ratio=Math.min(devicePixelRatio||1,2),w=el.clientWidth*ratio,h=el.clientHeight*ratio;if(el.width!==w||el.height!==h){el.width=w;el.height=h}drawPlaceholder(ctx,w,h,sceneId,time,parameters,effects)},[sceneId,time,parameters,effects])
 return <canvas ref={canvas} className="stage__canvas" aria-hidden="true"/>
}
function drawPlaceholder(ctx:CanvasRenderingContext2D,w:number,h:number,id:SceneId,t:number,p:StoryVisualParameters,effects:ActiveEffect[]){ctx.clearRect(0,0,w,h);const palettes={drift:['#f8f4e9','#a7c2c2'],growth:['#f5eee0','#c7b082'],navigation:['#faf4e4','#efc16f']} as const;const palette=palettes[id];const wash=ctx.createLinearGradient(0,0,w,h);wash.addColorStop(0,palette[0]);wash.addColorStop(1,palette[1]);ctx.fillStyle=wash;ctx.fillRect(0,0,w,h);const energy=effects.reduce((sum,e)=>sum+e.effectiveIntensity,0)
 ctx.globalAlpha=.16+(p.darkness??0)*.2;ctx.strokeStyle=id==='growth'?'#607653':'#527e83';ctx.lineWidth=Math.max(1,w/1100);for(let i=0;i<9;i++){ctx.beginPath();for(let x=0;x<w;x+=18){const y=h*(.53+i*.027)+Math.sin(x*.009+t*.6+i)*(8+(p.waveIntensity??.2)*18);ctx.lineTo(x,y)}ctx.stroke()}ctx.globalAlpha=1
 if(id==='drift'){ctx.save();ctx.translate(w*(.55+(p.horizontalDrift??.2)*.03*Math.sin(t*.3)),h*.57);ctx.fillStyle='#98725e55';ctx.strokeStyle='#755648';ctx.beginPath();ctx.ellipse(0,0,w*.045,h*.015,0,0,Math.PI);ctx.fill();ctx.stroke();ctx.restore()}
 if(id==='growth'||id==='navigation'){ctx.strokeStyle='#5e7658';ctx.lineWidth=w*.004;ctx.beginPath();ctx.moveTo(w*.57,h*.73);ctx.quadraticCurveTo(w*.55,h*.5,w*.58,h*.29);ctx.stroke();if(id==='growth'){ctx.fillStyle='#70896888';for(let i=0;i<7;i++){const a=i*2.4;ctx.beginPath();ctx.arc(w*.58+Math.cos(a)*w*.09*Math.min(1,t/25),h*.65-Math.sin(a)*h*.12*Math.min(1,t/25),3+energy*2,0,Math.PI*2);ctx.fill()}}}
 if(id==='navigation'){ctx.fillStyle='#dc963caa';for(let i=0;i<10;i++){const a=i*Math.PI/5;ctx.beginPath();ctx.ellipse(w*.58+Math.cos(a)*w*.033,h*.29+Math.sin(a)*h*.03,w*.03,h*.011,a,0,Math.PI*2);ctx.fill()}ctx.strokeStyle='#fff8d9aa';ctx.beginPath();ctx.moveTo(w*.15,h*.45);ctx.lineTo(w*.86,h*.45);ctx.stroke()}
 if((p.fogDensity??0)>0){ctx.fillStyle=`rgba(255,255,255,${Math.min(.7,p.fogDensity??0)})`;ctx.fillRect(0,0,w,h)}if((p.darkness??0)>0){ctx.fillStyle=`rgba(22,39,51,${p.darkness})`;ctx.fillRect(0,0,w,h)}}
