import { useEffect, useState } from 'react'
import { ActReader } from '../components/ActReader'; import { ChoiceScreen } from '../components/ChoiceScreen'; import { EndingScreen } from '../components/EndingScreen'; import { IntroScreen } from '../components/IntroScreen'; import { ProgressIndicator } from '../components/ProgressIndicator'
import { getCurrentBlock, goToNextBlock, goToPreviousBlock, recordChoice, resolveActContent, restartStory } from '../engine/storyEngine'; import { loadStory } from '../engine/storyLoader'; import { clearStoryState, loadStoryState, saveStoryState } from '../storage/storyStorage'; import type { StoryDefinition, StoryRuntimeState } from '../types/story'
export default function App() {
 const [story,setStory]=useState<StoryDefinition|null>(null), [state,setState]=useState<StoryRuntimeState>(restartStory), [saved,setSaved]=useState<StoryRuntimeState|null>(null); const [mode,setMode]=useState<'home'|'reading'>('home'), [error,setError]=useState<string|null>(null)
 useEffect(()=>{loadStory().then(value=>{setStory(value);setSaved(loadStoryState(value))}).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:'Une erreur inattendue est survenue.'))},[]); useEffect(()=>{if(story&&mode==='reading')saveStoryState(story,state)},[story,state,mode])
 if(error)return <main className="screen status"><h1>Le conte reste fermé</h1><p>{error}</p><button className="button" onClick={()=>location.reload()}>Réessayer</button></main>; if(!story)return <main className="screen status" aria-live="polite"><p>Le conte se prépare…</p></main>
 const start=(next=restartStory())=>{setState(next);setMode('reading')}; if(mode==='home')return <IntroScreen metadata={story.metadata} canResume={Boolean(saved)} onStart={()=>start()} onResume={()=>start(saved??restartStory())} onRestart={()=>{clearStoryState();setSaved(null);start()}} />
 const block=getCurrentBlock(story,state), next=()=>setState(value=>goToNextBlock(story,value)), previous=state.currentBlockIndex>0?()=>setState(goToPreviousBlock):undefined; if(!block)return <main className="screen status"><p>Ce passage est introuvable.</p></main>
 return <><header className="masthead"><span>{story.metadata.title}</span><ProgressIndicator current={state.currentBlockIndex} total={story.storyboard.length}/></header>{block.type==='act'&&(()=>{const content=resolveActContent(story.acts[block.module],state.responses);return <ActReader {...content} onNext={next} onPrevious={previous}/>})()}{block.type==='choice'&&<ChoiceScreen choice={story.choices[block.module]} selected={state.responses[block.module]?.[0]} onSelect={id=>setState(value=>recordChoice(value,block.module,id?[id]:[]))} onNext={next} onPrevious={previous}/>} {block.type==='pause'&&<ActReader title={story.pauses?.[block.module].title??'Pause'} text={story.pauses?.[block.module].text??''} onNext={next} onPrevious={previous}/>} {block.type==='ending'&&<EndingScreen ending={story.endings[block.module]} onReview={()=>setState(value=>({...value,currentBlockIndex:0,completed:false}))} onRestart={()=>{clearStoryState();start()}} onHome={()=>{setSaved(state);setMode('home')}}/>}</>
}
