import type { PoetryUniverse } from '../univers'

export const universes: PoetryUniverse[] = [
  {
    id: 'pierre',
    affinities: { heavy: 8, freeze: 5, last: 6, hurt: 2 },
    intros: ['Certaines pierres semblent fermer le passage.', 'Une pierre demeure au milieu du sentier.'],
    images: ['La mousse ne lui demande pas de disparaître.\nElle s’installe dans ses creux.', 'La pluie suit patiemment chaque fissure.\nLe lichen y dessine une rive.'],
    developments: ['Lentement, la surface change.\nUne couleur nouvelle apparaît.', 'Sous ce qui paraît immobile,\nla terre poursuit son mouvement.'],
    openings: ['Une racine trouve le bord de la pierre.', 'Une ligne claire traverse enfin la roche.'],
    endings: ['Une fissure suffit parfois.', 'Le sentier reste ouvert à la lumière.'],
  },
  {
    id: 'brume',
    affinities: { blur: 9, loop: 6, isolate: 2 },
    intros: ['La brume est entrée dans le paysage.', 'Au matin, les contours se sont retirés.'],
    images: ['Les arbres demeurent,\ninvisibles derrière le voile.', 'Une goutte suspend le jardin\nau bord de la vitre.'],
    developments: ['Les formes reviennent sans hâte,\nl’une après l’autre.', 'Le sentier apparaît par fragments,\nentre deux nappes blanches.'],
    openings: ['Une branche se précise dans l’air pâle.', 'Un peu de lumière rejoint la lisière.'],
    endings: ['L’horizon peut rester entrouvert.', 'Le jour commence au bord du voile.'],
  },
  {
    id: 'eau',
    affinities: { overflow: 9, invade: 7, loop: 2 },
    intros: ['L’eau a dépassé la ligne des rives.', 'Une eau profonde traverse le jardin.'],
    images: ['Elle emporte des feuilles,\npuis ralentit près des roseaux.', 'Sous la surface mouvante,\nles pierres gardent leur silence.'],
    developments: ['Le courant cherche une largeur nouvelle,\nentre les tiges souples.', 'L’écume se défait,\nlaissant paraître un reflet.'],
    openings: ['Une rive se dessine plus loin.', 'Un nénuphar retient un peu de ciel.'],
    endings: ['L’eau poursuit son passage vers le jour.', 'Au loin, la lumière touche la rive.'],
  },
  {
    id: 'feu',
    affinities: { burn: 9, hurt: 7, invade: 2 },
    intros: ['Une braise veille sous la cendre.', 'Le feu dessine un cercle dans la nuit.'],
    images: ['La flamme se tient droite,\npuis se courbe avec l’air.', 'Autour d’elle, le bois devient\nune matière plus légère.'],
    developments: ['La chaleur change lentement de forme,\ndu rouge à l’ambre.', 'Une étincelle rejoint la terre sombre\nsans troubler le silence.'],
    openings: ['Dans la cendre paraît une graine claire.', 'Une lumière demeure au bord du foyer.'],
    endings: ['L’aube recueille encore sa lueur.', 'La braise ouvre un passage dans l’ombre.'],
  },
  {
    id: 'nuit',
    affinities: { isolate: 9, last: 3, hurt: 2 },
    intros: ['La nuit a posé son encre sur le jardin.', 'Une heure silencieuse entoure la maison.'],
    images: ['Une fenêtre garde sa lumière,\nseule parmi les branches.', 'La lune dessine un chemin pâle\nentre les herbes.'],
    developments: ['Dans l’ombre, les graines demeurent,\nrecueillies sous la terre.', 'Le noir révèle peu à peu\nla présence des étoiles.'],
    openings: ['Une feuille capte la clarté lointaine.', 'Au bord du ciel, une nuance apparaît.'],
    endings: ['Le matin reste une ligne possible.', 'Une fenêtre demeure ouverte sur l’aube.'],
  },
  {
    id: 'vent',
    affinities: { invade: 6, loop: 6, breathe: 7 },
    intros: ['Le vent traverse les herbes hautes.', 'Un courant d’air soulève le jardin.'],
    images: ['Les tiges plient ensemble,\nsans perdre leur ancrage.', 'Une feuille tourne,\npuis se pose contre la terre.'],
    developments: ['L’air déplace les ombres,\npuis le parfum des feuilles.', 'Entre les branches,\nun espace se forme.'],
    openings: ['Une graine légère franchit la haie.', 'Le feuillage laisse passer le ciel.'],
    endings: ['Plus loin, l’air demeure ouvert.', 'Le vent porte encore un peu de lumière.'],
  },
  {
    id: 'graine',
    affinities: { change: 10, breathe: 8, freeze: 2 },
    intros: ['Une graine repose dans la terre sombre.', 'Sous la surface, une graine attend.'],
    images: ['Sa coque garde en silence\nla forme d’une première feuille.', 'L’eau rejoint la terre,\nla lumière demeure au-dessus.'],
    developments: ['Une racine très fine descend,\nattirée par la terre profonde.', 'Sans bruit, la coque s’entrouvre\nau contact du printemps.'],
    openings: ['Une pousse soulève quelques grains de terre.', 'Un vert fragile paraît dans la fissure.'],
    endings: ['La lumière rencontre une feuille nouvelle.', 'Le jardin s’ouvre à cette naissance discrète.'],
  },
  {
    id: 'arbre',
    affinities: { heavy: 4, last: 7, isolate: 4, change: 3 },
    intros: ['Un arbre tient le centre du jardin.', 'Le tronc garde la mémoire des saisons.'],
    images: ['Sous l’écorce, la sève poursuit\nson chemin invisible.', 'Les branches portent à la fois\nl’ombre et la lumière.'],
    developments: ['Chaque anneau demeure dans le bois,\ntracé autour du cœur.', 'Une feuille se détache,\nune autre forme déjà son bourgeon.'],
    openings: ['Une branche rejoint l’espace du ciel.', 'Au bout du rameau, le jour se déplie.'],
    endings: ['La canopée laisse une place au lointain.', 'Une saison nouvelle touche les feuilles.'],
  },
  {
    id: 'lumière',
    affinities: { blur: 5, freeze: 4, hurt: 4, change: 3 },
    intros: ['Une lumière basse traverse la pièce.', 'Le jour entre par une fente étroite.'],
    images: ['Il révèle la poussière en suspension,\npuis le bord d’une feuille.', 'Sur le mur, une forme claire\nse déplace avec les heures.'],
    developments: ['Les ombres changent de place\nsans disparaître.', 'La clarté se pose seulement\nsur ce qu’elle rencontre.'],
    openings: ['Un reflet atteint le fond du jardin.', 'La fenêtre dessine un passage doré.'],
    endings: ['Au-delà du cadre, le jour continue.', 'Une autre lumière peut encore entrer.'],
  },
]
