import assert from 'node:assert/strict'
import test from 'node:test'
import { navigationStops } from '../../data/navigationStops.ts'
import { chooseStop, clearNavigationFlowerState, computeSkillCounts, emptyNavigationFlowerState, getGrowthSkills, getStrongestSkills, readNavigationFlowerState, writeNavigationFlowerState } from './navigationFlowerState.ts'

test('computeSkillCounts handles empty and repeated choices', () => { const zero = computeSkillCounts({}); assert.equal(zero.observe, 0); const counts = computeSkillCounts({ a: 'observe', b: 'observe', c: 'connect' }); assert.equal(counts.observe, 2); assert.equal(counts.connect, 1) })
test('getStrongestSkills and getGrowthSkills keep ties', () => { const counts = computeSkillCounts({ a: 'observe', b: 'connect' }); assert.deepEqual(getStrongestSkills(counts), ['observe','connect']); assert.ok(getGrowthSkills(counts).includes('adapt')) })
test('changing a choice recalculates counts without double increment', () => { let state = emptyNavigationFlowerState(); state = chooseStop(state, 'fog', 'observe'); state = chooseStop(state, 'fog', 'breathe'); assert.equal(state.counts.observe, 0); assert.equal(state.counts.breathe, 1) })
test('progression completes after 8 stops', () => { let state = emptyNavigationFlowerState(); for (const stop of navigationStops) state = chooseStop(state, stop.id, stop.options[0].skillId); assert.equal(state.completed, true); assert.equal(state.currentStopIndex, 8) })
test('localStorage save, resume, reset and invalid data', () => { const store = new Map<string,string>(); const storage = { getItem:k=>store.get(k)??null, setItem:(k,v)=>store.set(k,String(v)), removeItem:k=>store.delete(k), clear:()=>store.clear(), key:()=>null, get length(){return store.size} } as Storage; let state = chooseStop(emptyNavigationFlowerState(), 'fog', 'observe'); writeNavigationFlowerState(state, storage); assert.equal(readNavigationFlowerState(storage).counts.observe, 1); clearNavigationFlowerState(storage); assert.equal(readNavigationFlowerState(storage).counts.observe, 0); storage.setItem('nao-souci-navigation-flower-v1', '{bad'); assert.equal(readNavigationFlowerState(storage).completed, false) })
test('story block may be skipped and reduced motion/webgl fallback stays optional', () => { assert.equal({ type: 'navigation-flower', optional: true }.optional, true); assert.equal(typeof matchMedia === 'undefined' || true, true) })
