import { navigationSkillIds, type NavigationSkill } from '../../data/navigationSkills.ts'
import { navigationStops } from '../../data/navigationStops.ts'

export const NAVIGATION_FLOWER_STORAGE_KEY = 'nao-souci-navigation-flower-v1'
export interface NavigationFlowerState { currentStopIndex: number; selections: Record<string, NavigationSkill>; counts: Record<NavigationSkill, number>; completed: boolean; reflection?: string; completedAt?: string }
export const emptyCounts = (): Record<NavigationSkill, number> => Object.fromEntries(navigationSkillIds.map(id => [id, 0])) as Record<NavigationSkill, number>
export const emptyNavigationFlowerState = (): NavigationFlowerState => ({ currentStopIndex: 0, selections: {}, counts: emptyCounts(), completed: false })
export function computeSkillCounts(selections: Record<string, NavigationSkill>): Record<NavigationSkill, number> { const counts = emptyCounts(); for (const skill of Object.values(selections)) if (skill in counts) counts[skill] += 1; return counts }
export function getStrongestSkills(counts: Record<NavigationSkill, number>): NavigationSkill[] { const max = Math.max(...navigationSkillIds.map(id => counts[id])); return navigationSkillIds.filter(id => counts[id] === max) }
export function getGrowthSkills(counts: Record<NavigationSkill, number>): NavigationSkill[] { const min = Math.min(...navigationSkillIds.map(id => counts[id])); return navigationSkillIds.filter(id => counts[id] === min) }
export function chooseStop(state: NavigationFlowerState, stopId: string, skillId: NavigationSkill): NavigationFlowerState { const selections = { ...state.selections, [stopId]: skillId }; const counts = computeSkillCounts(selections); const index = navigationStops.findIndex(stop => stop.id === stopId); const nextIndex = Math.min(index + 1, navigationStops.length); return { ...state, selections, counts, currentStopIndex: nextIndex, completed: Object.keys(selections).length >= navigationStops.length, completedAt: Object.keys(selections).length >= navigationStops.length ? (state.completedAt ?? new Date().toISOString()) : undefined } }
export function goToFlowerStop(state: NavigationFlowerState, index: number): NavigationFlowerState { return { ...state, currentStopIndex: Math.min(Math.max(index, 0), navigationStops.length - 1), completed: false, completedAt: undefined } }
export function readNavigationFlowerState(storage: Storage = localStorage): NavigationFlowerState { try { const parsed = JSON.parse(storage.getItem(NAVIGATION_FLOWER_STORAGE_KEY) ?? 'null') as Partial<NavigationFlowerState> | null; if (!parsed || typeof parsed !== 'object') return emptyNavigationFlowerState(); const selections = Object.fromEntries(Object.entries(parsed.selections ?? {}).filter(([stopId, skill]) => navigationStops.some(stop => stop.id === stopId) && navigationSkillIds.includes(skill as NavigationSkill))) as Record<string, NavigationSkill>; const counts = computeSkillCounts(selections); const completed = Boolean(parsed.completed) && Object.keys(selections).length === navigationStops.length; return { currentStopIndex: completed ? navigationStops.length : Math.min(Math.max(Number(parsed.currentStopIndex) || 0, 0), navigationStops.length - 1), selections, counts, completed, reflection: typeof parsed.reflection === 'string' ? parsed.reflection : '', completedAt: typeof parsed.completedAt === 'string' ? parsed.completedAt : undefined } } catch { return emptyNavigationFlowerState() } }
export function writeNavigationFlowerState(state: NavigationFlowerState, storage: Storage = localStorage) { storage.setItem(NAVIGATION_FLOWER_STORAGE_KEY, JSON.stringify(state)) }
export function clearNavigationFlowerState(storage: Storage = localStorage) { storage.removeItem(NAVIGATION_FLOWER_STORAGE_KEY) }
